version: '3.8'
services:
  api:
    image: quran-api
    build: 
      context: .
      dockerfile: Dockerfile
      target: deploy
    ports:
      - 3001:3001
  database:
    image: postgres:latest
    container_name: psql-db
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
volumes:
  postgres:
    name: psql-vol