apiVersion: apps/v1
kind: Deployment
metadata:
  name: quran-api-depl
spec:
  replacation: 1
  selector:
    matchLabels:
      app: quran-api
  template:
    metadata:
      labels:
        app: quran-api
    spec:
      containers:
      - name: quran-api
        image: mehradi/quran-api:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: quran-api-srv
spec:
  selector:
    app: quran-api-srv
  ports:
  - port: 3001
    targetPort: 3001
        
