apiVersion: v1
kind: Secret
metadata:
  name: postgresdb-secret
type: Opaque
data:
  POSTGRES_DB: <DB>
  POSTGRES_USER: <Username>
  POSTGRES_PASSWORD: <Password>
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresdb-pv
  labels:
    type: local
    app: postgresdb
spec:
  capacity:
    storage: <Size>
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
     path: "/data/db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresdb-pvc
spec:
  storageClassName: manual
  resources:
    requests:
      storage: <Size>
  accessModes:
    - ReadWriteMany
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
      - name: postgresdb
        image: postgres
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgresdb-secret
                key: POSTGRES_USER  
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgresdb-secret
                key: POSTGRES_DB  
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresdb-secret
                key: POSTGRES_PASSWORD    
        ports:
          - containerPort: 5432
        volumeMounts:
          - name: data
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgresdb-pvc  
---
apiVersion: v1
kind: Service
metadata:
  name: postgresdb-svc
spec:
  selector:
    app: postgresdb
  ports:
  - protocol: TCP
    name: http
    port: 5432
    targetPort: 5432
            
    
     
  
